language: python
python:
  - "2.7"
  - "2.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
script:
  - "coverage run --source=pyfav setup.py test"
after_success:
  coveralls
